### ISSUE TITLE
Initial TODO

### ISSUE THREAD

**Issue by sebhoerl** [eqasim-org/matsim-sharing#1]
We have now put the code online in this repository. But there are still a couple of point on the TODO list to make a complete contrib:

- [ ] Scoring implementation (for missed rentals, the rest is done by the mode-specific scoring)
- [ ] Some basic analysis output
- [ ] Add service area constraint
- [ ] Integration with MATSim `Vehicle`
  - If the `bicycle` contrib or `car` is used as the underlying mode, the vehicle ID in the service file should correspond to registere `Vehicle`s
 - [ ] Integration with EVs (from the `ev` contrib, to calculate the energy consumption of the shared vehicles)
 - [x] Create test scenario
 - [ ] Create unit tests
 - [ ] Improve documentation
